[package]
name = "fast_socks"
version = "0.1.0"
edition = "2024"

[dependencies]
fast-socks5 = { git = "https://github.com/dizda/fast-socks5.git", branch = "master" }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
structopt = "0.3"
env_logger = "0.10"
log = "0.4"